// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD98bte2bR6kSgQrpQhV9NdsMV_6-RJT_M',
    appId: '1:161929574535:web:5fdfddfd48753077e86022',
    messagingSenderId: '161929574535',
    projectId: 'lamarktempmonitor',
    authDomain: 'lamarktempmonitor.firebaseapp.com',
    storageBucket: 'lamarktempmonitor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi9B8k8KAKyS1LrtmHAT-4jnXdmHWBXsE',
    appId: '1:161929574535:android:347c759f4d1a54dae86022',
    messagingSenderId: '161929574535',
    projectId: 'lamarktempmonitor',
    storageBucket: 'lamarktempmonitor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfZxQyWjS9jP5mWeuWdQSJYug8F3NMSpE',
    appId: '1:161929574535:ios:4d6617465938ebbce86022',
    messagingSenderId: '161929574535',
    projectId: 'lamarktempmonitor',
    storageBucket: 'lamarktempmonitor.appspot.com',
    iosClientId: '161929574535-35n926k2oobo3jntusq6jpqr4pongl5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.lamarkTemp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfZxQyWjS9jP5mWeuWdQSJYug8F3NMSpE',
    appId: '1:161929574535:ios:4d6617465938ebbce86022',
    messagingSenderId: '161929574535',
    projectId: 'lamarktempmonitor',
    storageBucket: 'lamarktempmonitor.appspot.com',
    iosClientId: '161929574535-35n926k2oobo3jntusq6jpqr4pongl5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.lamarkTemp',
  );
}
